const countries = [
    { sc_id: '40', sc_name: 'USA', sc_price_perkg: '635.59', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '80', sc_name: 'USA', sc_price_perkg: '735.59', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '41', sc_name: 'Canada', sc_price_perkg: '720.33', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '81', sc_name: 'Canada', sc_price_perkg: '820.33', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '42', sc_name: 'Europe', sc_price_perkg: '677.96', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '82', sc_name: 'Europe', sc_price_perkg: '777.96', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '43', sc_name: 'UAE', sc_price_perkg: '338.98', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '83', sc_name: 'UAE', sc_price_perkg: '438.98', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '44', sc_name: 'Qatar', sc_price_perkg: '508.47', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '84', sc_name: 'Qatar', sc_price_perkg: '608.47', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '45', sc_name: 'Kuwait', sc_price_perkg: '508.47', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '85', sc_name: 'Kuwait', sc_price_perkg: '608.47', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '46', sc_name: 'Oman', sc_price_perkg: '508.47', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '86', sc_name: 'Oman', sc_price_perkg: '608.47', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '47', sc_name: 'Bahrain', sc_price_perkg: '508.47', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '87', sc_name: 'Bahrain', sc_price_perkg: '608.47', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '48', sc_name: 'Saudi Arabia', sc_price_perkg: '508.47', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '88', sc_name: 'Saudi Arabia', sc_price_perkg: '608.47', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '49', sc_name: 'Singapore', sc_price_perkg: '338.98', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '89', sc_name: 'Singapore', sc_price_perkg: '438.98', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '50', sc_name: 'Malaysia', sc_price_perkg: '593.22', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '90', sc_name: 'Malaysia', sc_price_perkg: '693.22', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '51', sc_name: 'Thailand', sc_price_perkg: '762.71', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '52', sc_name: 'Hong Kong', sc_price_perkg: '338.98', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '91', sc_name: 'Hong Kong', sc_price_perkg: '438.98', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '53', sc_name: 'Sri Lanka', sc_price_perkg: '400.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '54', sc_name: 'Bangladesh', sc_price_perkg: '508.47', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '92', sc_name: 'Bangladesh', sc_price_perkg: '608.47', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '55', sc_name: 'Nepal', sc_price_perkg: '338.98', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '93', sc_name: 'Nepal', sc_price_perkg: '438.98', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '57', sc_name: 'Australia', sc_price_perkg: '762.71', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '94', sc_name: 'Australia', sc_price_perkg: '862.71', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '58', sc_name: 'New Zealand', sc_price_perkg: '847.45', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '95', sc_name: 'New Zealand', sc_price_perkg: '947.45', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '59', sc_name: 'Japan', sc_price_perkg: '800.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '60', sc_name: 'Indonesia', sc_price_perkg: '762.00', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '96', sc_name: 'Indonesia', sc_price_perkg: '862.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '61', sc_name: 'South Korea', sc_price_perkg: '762.00', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '97', sc_name: 'South Korea', sc_price_perkg: '862.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '62', sc_name: 'China', sc_price_perkg: '750.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '63', sc_name: 'PNG', sc_price_perkg: '780.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '64', sc_name: 'Fiji', sc_price_perkg: '750.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '65', sc_name: 'South America', sc_price_perkg: '900.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '66', sc_name: 'Turkey', sc_price_perkg: '700.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '67', sc_name: 'Georgia', sc_price_perkg: '677.96', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '98', sc_name: 'Georgia', sc_price_perkg: '777.96', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '68', sc_name: 'Greece', sc_price_perkg: '700.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '69', sc_name: 'Ukraine', sc_price_perkg: '800.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '70', sc_name: 'Armenia', sc_price_perkg: '720.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '71', sc_name: 'Uzbekistan', sc_price_perkg: '750.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '72', sc_name: 'Kazakhstan', sc_price_perkg: '750.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '73', sc_name: 'Norway', sc_price_perkg: '900.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '74', sc_name: 'Philippines', sc_price_perkg: '800.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '75', sc_name: 'UK', sc_price_perkg: '508.47', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '99', sc_name: 'UK', sc_price_perkg: '608.47', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '76', sc_name: 'South Africa', sc_price_perkg: '932.20', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '77', sc_name: 'Switzerland', sc_price_perkg: '900.00', sc_transit_days: null, service_type: 'standard' },
    { sc_id: '78', sc_name: 'Germany', sc_price_perkg: '850.00', sc_transit_days: null, service_type: 'premium' },
    { sc_id: '79', sc_name: 'Maldives', sc_price_perkg: '880.00', sc_transit_days: null, service_type: 'premium' }
  ];
  
  module.exports = countries;
  